# Generated by Django 3.2 on 2021-05-02 13:54

import coffee_shop.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0003_auto_20210502_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='zipcode',
            field=models.CharField(default='', max_length=100, validators=[coffee_shop.validators.validate_zipcode]),
            preserve_default=False,
        ),
    ]
