# Generated by Django 3.2 on 2021-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0004_auto_20210502_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(None, 'Please select a drink type'), ('A', 'Americano'), ('C', 'Cappuccino'), ('CB', 'Cold Brew Coffee')], max_length=10)),
                ('size', models.CharField(choices=[(None, 'Please select a size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
